# Generated by Django 4.2.5 on 2023-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bttnauth', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authtokens',
            index=models.Index(fields=['access_token'], name='bttnauth_au_access__933231_idx'),
        ),
    ]
